import { describe, expect, test } from 'vitest';
import { mkdtemp, readFile, rm, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { foldEntries, partitionEntries, type LedgerEntryWire } from './ledger-fold';
import { appendToLedgerFile, getLedgerPath, getUtcMonth } from '../ledger-fold';

const MONTH = '2026-08';

const HEADER =
  '# Gate ledger — 2026-08 · *derived, not authored: generated by scripts/ledger-fold.ts ' +
  "from the governor's ledger; evidence for dreams, never interpretation (Principles 1/2/7).*";

const NOTE =
  '*`door_name` is a legacy column name; an exchange row names a session, not a door.*';

/** UTC epoch ms inside MONTH. */
function at(day: number, hour: number, minute: number): number {
  return Date.UTC(2026, 7, day, hour, minute, 0, 0);
}

function row(over: Partial<LedgerEntryWire>): LedgerEntryWire {
  return {
    ts: at(3, 9, 0),
    sub: 'lease:SESS1',
    service: 'stream',
    verb: 'socket',
    detail: '',
    allowed: 1,
    ...over,
  };
}

/** The slice of the document from one `## ` heading to the next (or the end). */
function sectionOf(doc: string, heading: string): string {
  const start = doc.indexOf(`## ${heading}`);
  expect(start, `section "${heading}" is missing`).toBeGreaterThanOrEqual(0);
  const rest = doc.indexOf('\n## ', start + 1);
  return (rest === -1 ? doc.slice(start) : doc.slice(start, rest)).trimEnd();
}

/** The Step 1 fixture: an exchange, three socket opens, two theft rows, two package reads. */
function fixture(): LedgerEntryWire[] {
  return [
    row({ ts: at(3, 9, 0), sub: 'lease:SESS1', verb: 'exchange', detail: 'new session' }),
    row({ ts: at(3, 9, 1), sub: 'lease:SESS1', verb: 'socket', detail: 'open token_id=t1' }),
    row({ ts: at(3, 9, 2), sub: 'lease:SESS1', verb: 'socket', detail: 'open token_id=t2' }),
    row({ ts: at(3, 9, 3), sub: 'lease:SESS2', verb: 'socket', detail: 'open token_id=t3' }),
    row({
      ts: at(4, 11, 30),
      sub: 'lease:L1',
      verb: 'ticket-reused',
      detail: 'token_id=t9 reused at 10s interval',
      allowed: 0,
    }),
    row({
      ts: at(4, 11, 31),
      sub: 'lease:L2',
      verb: 'killed',
      detail: 'door=browser:tab lease killed: rotation replay',
      allowed: 0,
    }),
    row({
      // package_list/wake_julian/visit_agent all ledger as service:'package',
      // verb:'list' with an empty detail (broker/src/mcp.ts:562).
      ts: at(5, 8, 5),
      sub: 'lease:SESS1',
      service: 'package',
      verb: 'list',
      detail: '',
    }),
    row({
      // package_read ledgers as service:'package', verb:'read', detail
      // `path=<p> pin=<pin> class=<cls>` (broker/src/mcp.ts readDetail).
      ts: at(5, 8, 6),
      sub: 'lease:SESS1',
      service: 'package',
      verb: 'read',
      detail: 'path=soul/01-naming.md pin=4299b3b0a1b2 class=ok',
    }),
  ];
}

describe('foldEntries — document shape', () => {
  test('an empty month renders the whole document exactly', () => {
    expect(foldEntries([], MONTH)).toBe(
      [
        HEADER,
        '',
        NOTE,
        '',
        '## Wakings & package reads',
        '',
        '*(none)*',
        '',
        '## Theft signals',
        '',
        '*(none)*',
        '',
        '## Routine delegated-session traffic',
        '',
        '*(none)*',
        '',
      ].join('\n'),
    );
  });

  test('the header marks the document derived-not-authored', () => {
    const doc = foldEntries([], MONTH);
    expect(doc.split('\n')[0]).toBe(HEADER);
    expect(doc).toContain('derived, not authored');
    expect(doc).toContain('generated by scripts/ledger-fold.ts');
    expect(doc).toContain('Principles 1/2/7');
  });

  test('the holder/session column carries the legacy-name note', () => {
    expect(foldEntries([], MONTH)).toContain(NOTE);
  });

  test('three sections in order: wakings, theft signals, routine traffic', () => {
    const doc = foldEntries([], MONTH);
    const wakingsIdx = doc.indexOf('## Wakings & package reads');
    const theftIdx = doc.indexOf('## Theft signals');
    const routineIdx = doc.indexOf('## Routine delegated-session traffic');
    expect(wakingsIdx).toBeGreaterThan(0);
    expect(theftIdx).toBeGreaterThan(wakingsIdx);
    expect(routineIdx).toBeGreaterThan(theftIdx);
  });
});

describe('foldEntries — the three sections over the fixture', () => {
  test('wakings section renders every package/wake row first-class', () => {
    expect(sectionOf(foldEntries(fixture(), MONTH), 'Wakings & package reads')).toBe(
      [
        '## Wakings & package reads',
        '',
        '| when (UTC) | holder/session | verb | detail |',
        '|---|---|---|---|',
        '| 2026-08-05 08:05 | lease:SESS1 | list |  |',
        '| 2026-08-05 08:06 | lease:SESS1 | read | path=soul/01-naming.md pin=4299b3b0a1b2 class=ok |',
      ].join('\n'),
    );
  });

  test('theft signals stay uncollapsed, verbatim, with timestamp and token_id', () => {
    expect(sectionOf(foldEntries(fixture(), MONTH), 'Theft signals')).toBe(
      [
        '## Theft signals',
        '',
        '| when (UTC) | holder/session | verb | detail | token_id |',
        '|---|---|---|---|---|',
        '| 2026-08-04 11:30 | lease:L1 | ticket-reused | token_id=t9 reused at 10s interval | t9 |',
        '| 2026-08-04 11:31 | lease:L2 | killed | door=browser:tab lease killed: rotation replay | — |',
      ].join('\n'),
    );
  });

  test('routine traffic collapses to exact counts per holder/session × verb', () => {
    expect(sectionOf(foldEntries(fixture(), MONTH), 'Routine delegated-session traffic')).toBe(
      [
        '## Routine delegated-session traffic',
        '',
        '| holder/session | verb | count |',
        '|---|---|---|',
        '| lease:SESS1 | exchange | 1 |',
        '| lease:SESS1 | socket | 2 |',
        '| lease:SESS2 | socket | 1 |',
      ].join('\n'),
    );
  });

  test('the routine table is emitted exactly once, header and separator included', () => {
    const doc = foldEntries(fixture(), MONTH);
    const headers = doc.match(/\| holder\/session \| verb \| count \|/g) ?? [];
    const separators = doc.match(/^\|---\|---\|---\|$/gm) ?? [];
    expect(headers).toHaveLength(1);
    expect(separators).toHaveLength(1);
  });
});

describe('foldEntries — theft is never collapsed into routine', () => {
  test('a theft row is not double-reported as routine traffic', () => {
    const doc = foldEntries(fixture(), MONTH);
    const routine = sectionOf(doc, 'Routine delegated-session traffic');
    expect(routine).not.toContain('ticket-reused');
    expect(routine).not.toContain('killed');
    expect(routine).not.toContain('lease:L1');
    expect(routine).not.toContain('lease:L2');
  });

  test('a theft verb with an empty detail is still a theft signal, never routine', () => {
    const entries = [
      row({ ts: at(6, 1, 0), sub: 'lease:L3', verb: 'ticket-reused', detail: '', allowed: 0 }),
      row({ ts: at(6, 1, 1), sub: 'lease:L4', verb: 'killed', detail: '', allowed: 0 }),
    ];
    const doc = foldEntries(entries, MONTH);
    expect(sectionOf(doc, 'Theft signals')).toBe(
      [
        '## Theft signals',
        '',
        '| when (UTC) | holder/session | verb | detail | token_id |',
        '|---|---|---|---|---|',
        '| 2026-08-06 01:00 | lease:L3 | ticket-reused |  | — |',
        '| 2026-08-06 01:01 | lease:L4 | killed |  | — |',
      ].join('\n'),
    );
    expect(sectionOf(doc, 'Routine delegated-session traffic')).toBe(
      ['## Routine delegated-session traffic', '', '*(none)*'].join('\n'),
    );
  });

  test('a class=integrity-latched package read surfaces as a theft signal', () => {
    const detail = 'path=soul/01-naming.md pin=4299b3b0a1b2 class=integrity-latched';
    const doc = foldEntries(
      [row({ ts: at(7, 12, 0), sub: 'lease:L5', service: 'package', verb: 'read', detail })],
      MONTH,
    );
    expect(sectionOf(doc, 'Theft signals')).toContain(detail);
    expect(sectionOf(doc, 'Wakings & package reads')).toContain('*(none)*');
  });

  test('a class=integrity (double-mismatch) package read surfaces as a theft signal', () => {
    const detail = 'path=soul/01-naming.md pin=none class=integrity';
    const doc = foldEntries(
      [row({ ts: at(7, 12, 1), sub: 'lease:L6', service: 'package', verb: 'read', detail })],
      MONTH,
    );
    expect(sectionOf(doc, 'Theft signals')).toContain(detail);
    expect(sectionOf(doc, 'Wakings & package reads')).toContain('*(none)*');
  });

  test('the partition is exhaustive and disjoint — no in-month row is dropped', () => {
    const entries = [...fixture(), row({ ts: at(8, 3, 0), sub: 'user:marcus', service: 'mail', verb: 'send' })];
    const { wakings, theft, routine } = partitionEntries(entries);
    expect(wakings.length + theft.length + routine.length).toBe(entries.length);
    const seen = new Set([...wakings, ...theft, ...routine]);
    expect(seen.size).toBe(entries.length);
  });
});

describe('foldEntries — details are carried whole', () => {
  test('a detail longer than 100 characters is never truncated', () => {
    const detail =
      'pin moved `cc7f5fe0a1b2c3d4e5f60718293a4b5c6d7e8f90` → `4299b3b0a1b2c3d4e5f60718293a4b5c6d7e8f90`; run package_list, then re-read from the top';
    expect(detail.length).toBeGreaterThan(100);
    const doc = foldEntries(
      [row({ ts: at(9, 4, 0), sub: 'lease:L6', verb: 'ticket-reused', detail, allowed: 0 })],
      MONTH,
    );
    expect(doc).toContain(detail);
  });

  test('a pipe in a detail is escaped so the table row stays well-formed', () => {
    const doc = foldEntries(
      [
        row({
          ts: at(9, 5, 0),
          sub: 'lease:L7',
          service: 'package',
          verb: 'read',
          detail: 'path=a|b',
        }),
      ],
      MONTH,
    );
    const dataRow = sectionOf(doc, 'Wakings & package reads').split('\n')[4];
    expect(dataRow).toBe('| 2026-08-09 05:00 | lease:L7 | read | path=a\\|b |');
  });
});

describe('foldEntries — the month is a filter, not just a caption', () => {
  test('rows outside the requested UTC month are excluded from every section', () => {
    const other = [
      { ts: Date.UTC(2026, 6, 31, 23, 59), service: 'package', verb: 'read', detail: 'july read' },
      { ts: Date.UTC(2026, 8, 1, 0, 0), service: 'package', verb: 'read', detail: 'september read' },
      { ts: Date.UTC(2026, 6, 15, 0, 0), verb: 'ticket-reused', detail: 'july theft' },
      { ts: Date.UTC(2026, 8, 15, 0, 0), verb: 'socket', detail: 'september socket' },
    ].map((o) => row({ ...o, sub: 'lease:OTHER' }));

    const doc = foldEntries([...other, ...fixture()], MONTH);
    expect(doc).not.toContain('lease:OTHER');
    expect(doc).not.toContain('july');
    expect(doc).not.toContain('september');
    expect(sectionOf(doc, 'Routine delegated-session traffic')).toBe(
      [
        '## Routine delegated-session traffic',
        '',
        '| holder/session | verb | count |',
        '|---|---|---|',
        '| lease:SESS1 | exchange | 1 |',
        '| lease:SESS1 | socket | 2 |',
        '| lease:SESS2 | socket | 1 |',
      ].join('\n'),
    );
  });

  test('a month with no rows of its own renders as empty, not as another month', () => {
    const doc = foldEntries(fixture(), '2026-09');
    expect(doc).toContain('# Gate ledger — 2026-09 · ');
    expect(doc).not.toContain('lease:SESS1');
    expect(doc).not.toContain('ticket-reused');
  });

  test('getUtcMonth reads the UTC month of a date', () => {
    expect(getUtcMonth(new Date(Date.UTC(2026, 7, 13, 1, 32)))).toBe('2026-08');
    expect(getUtcMonth(new Date(Date.UTC(2026, 11, 31, 23, 59)))).toBe('2026-12');
  });
});

describe('appendToLedgerFile — append-only on a real file', () => {
  async function withTempDir(fn: (dir: string) => Promise<void>): Promise<void> {
    const dir = await mkdtemp(join(tmpdir(), 'ledger-fold-'));
    try {
      await fn(dir);
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  }

  test('the first run creates memory/ledger/, marks its own run time, and writes the fold', async () => {
    await withTempDir(async (dir) => {
      const path = getLedgerPath(join(dir, 'memory', 'ledger'), MONTH);
      const doc = foldEntries(fixture(), MONTH);
      await appendToLedgerFile(path, doc, new Date(Date.UTC(2026, 7, 13, 1, 32)));

      expect((await stat(join(dir, 'memory', 'ledger'))).isDirectory()).toBe(true);
      expect(await readFile(path, 'utf8')).toBe(
        `*Appended run — 2026-08-13T01:32:00.000Z*\n\n${doc}`,
      );
    });
  });

  test('a second fold appended to existing content leaves prior text byte-identical', async () => {
    await withTempDir(async (dir) => {
      const path = getLedgerPath(join(dir, 'memory', 'ledger'), MONTH);
      const first = foldEntries(fixture(), MONTH);
      await appendToLedgerFile(path, first, new Date(Date.UTC(2026, 7, 13, 1, 32)));
      const afterFirst = await readFile(path, 'utf8');

      const second = foldEntries(
        [row({ ts: at(20, 6, 0), sub: 'lease:SESS9', verb: 'exchange', detail: 'later session' })],
        MONTH,
      );
      await appendToLedgerFile(path, second, new Date(Date.UTC(2026, 7, 20, 6, 30)));
      const afterSecond = await readFile(path, 'utf8');

      expect(afterSecond.slice(0, afterFirst.length)).toBe(afterFirst);
      expect(afterSecond).toBe(
        `${afterFirst}\n\n---\n\n*Appended run — 2026-08-20T06:30:00.000Z*\n\n${second}`,
      );
      expect(afterSecond).toContain('| lease:SESS9 | exchange | 1 |');
    });
  });

  test('getLedgerPath names the file for its month', () => {
    expect(getLedgerPath('/x/memory/ledger', '2026-08')).toBe('/x/memory/ledger/2026-08.md');
  });
});
